### ISSUE TITLE
Viewport and Interval settings are not saved between sessions

### ISSUE THREAD

**Issue by Basssiiie** [fidwell/OpenRct2-Screenshotter#5]
Hey,

It would be nice if the chosen viewport/interval settings are saved between sessions. If I restart the game, all settings are reset to their defaults. I used your plugin to make [this timelapse](https://www.reddit.com/r/rct/comments/nvyqwp/trackless_darkride_tied_2nd_place_in_dkmp_contest/) but one of the days I forgot to set the rotation angle to "all four" again so I had to manually go back to my backup saves to get the missing screenshots for that day. 😢 

You can easily save the configuration settings for the plugin using the [shared storage API](https://github.com/OpenRCT2/OpenRCT2/blob/6b1141b5a2636f1459d178f2d689275525c8ea7f/distribution/openrct2.d.ts#L183).

Thanks!

**Comment by fidwell** [comment]
Great idea! I will look into this
